CREATE TABLE {prefix}ido_rounds (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  round_name varchar(100) NOT NULL DEFAULT '',
  status varchar(16) NOT NULL DEFAULT 'active',
  starts_at datetime DEFAULT NULL,
  ends_at datetime DEFAULT NULL,
  completed_at datetime DEFAULT NULL,
  created_at datetime DEFAULT NULL,
  PRIMARY KEY  (id),
  KEY status (status)
) {charset_collate};
CREATE TABLE {prefix}ido_kingdoms (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  round_id bigint(20) unsigned NOT NULL DEFAULT 0,
  user_id bigint(20) unsigned NOT NULL DEFAULT 0,
  kingdom_name varchar(60) NOT NULL DEFAULT '',
  ruler_name varchar(60) NOT NULL DEFAULT '',
  turns bigint(20) NOT NULL DEFAULT 0,
  turns_spent bigint(20) NOT NULL DEFAULT 0,
  last_turn_grant date DEFAULT NULL,
  land bigint(20) NOT NULL DEFAULT 0,
  land_in_progress bigint(20) NOT NULL DEFAULT 0,
  gold bigint(20) NOT NULL DEFAULT 0,
  grain bigint(20) NOT NULL DEFAULT 0,
  iron bigint(20) NOT NULL DEFAULT 0,
  peasants bigint(20) NOT NULL DEFAULT 0,
  b_homestead bigint(20) NOT NULL DEFAULT 0,
  b_farmstead bigint(20) NOT NULL DEFAULT 0,
  b_mint bigint(20) NOT NULL DEFAULT 0,
  b_foundry bigint(20) NOT NULL DEFAULT 0,
  b_barracks bigint(20) NOT NULL DEFAULT 0,
  b_fortification bigint(20) NOT NULL DEFAULT 0,
  u_pawn bigint(20) NOT NULL DEFAULT 0,
  u_legionnaire bigint(20) NOT NULL DEFAULT 0,
  u_centurion bigint(20) NOT NULL DEFAULT 0,
  u_ballista_legion bigint(20) NOT NULL DEFAULT 0,
  catapults bigint(20) NOT NULL DEFAULT 0,
  catapults_in_progress bigint(20) NOT NULL DEFAULT 0,
  agents bigint(20) NOT NULL DEFAULT 0,
  networth bigint(20) NOT NULL DEFAULT 0,
  protection_until datetime DEFAULT NULL,
  is_defeated tinyint(1) NOT NULL DEFAULT 0,
  attacks_made bigint(20) NOT NULL DEFAULT 0,
  attacks_won bigint(20) NOT NULL DEFAULT 0,
  attacks_suffered bigint(20) NOT NULL DEFAULT 0,
  land_taken bigint(20) NOT NULL DEFAULT 0,
  land_lost bigint(20) NOT NULL DEFAULT 0,
  created_at datetime DEFAULT NULL,
  last_seen datetime DEFAULT NULL,
  PRIMARY KEY  (id),
  UNIQUE KEY round_user (round_id,user_id),
  UNIQUE KEY round_kingdom_name (round_id,kingdom_name),
  UNIQUE KEY round_ruler_name (round_id,ruler_name),
  KEY round_networth (round_id,networth),
  KEY user_id (user_id)
) {charset_collate};
CREATE TABLE {prefix}ido_constructions (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  round_id bigint(20) unsigned NOT NULL DEFAULT 0,
  kingdom_id bigint(20) unsigned NOT NULL DEFAULT 0,
  kind varchar(16) NOT NULL DEFAULT 'building',
  building varchar(32) NOT NULL DEFAULT '',
  qty int(11) NOT NULL DEFAULT 0,
  ready_on date DEFAULT NULL,
  created_at datetime DEFAULT NULL,
  PRIMARY KEY  (id),
  KEY kingdom_ready (kingdom_id,ready_on),
  KEY round_id (round_id)
) {charset_collate};
CREATE TABLE {prefix}ido_listings (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  round_id bigint(20) unsigned NOT NULL DEFAULT 0,
  seller_kingdom_id bigint(20) unsigned NOT NULL DEFAULT 0,
  item_kind varchar(16) NOT NULL DEFAULT 'resource',
  item_key varchar(32) NOT NULL DEFAULT '',
  qty bigint(20) NOT NULL DEFAULT 0,
  unit_price bigint(20) NOT NULL DEFAULT 0,
  status varchar(16) NOT NULL DEFAULT 'open',
  created_at datetime DEFAULT NULL,
  expires_at datetime DEFAULT NULL,
  PRIMARY KEY  (id),
  KEY round_status (round_id,status),
  KEY seller_kingdom_id (seller_kingdom_id)
) {charset_collate};
CREATE TABLE {prefix}ido_battles (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  round_id bigint(20) unsigned NOT NULL DEFAULT 0,
  attacker_kingdom_id bigint(20) unsigned NOT NULL DEFAULT 0,
  defender_kingdom_id bigint(20) unsigned NOT NULL DEFAULT 0,
  attack_type varchar(16) NOT NULL DEFAULT 'conquest',
  outcome varchar(16) NOT NULL DEFAULT 'repelled',
  offence_power bigint(20) NOT NULL DEFAULT 0,
  defence_power bigint(20) NOT NULL DEFAULT 0,
  land_taken int(11) NOT NULL DEFAULT 0,
  loot_gold bigint(20) NOT NULL DEFAULT 0,
  loot_grain bigint(20) NOT NULL DEFAULT 0,
  loot_iron bigint(20) NOT NULL DEFAULT 0,
  buildings_razed int(11) NOT NULL DEFAULT 0,
  catapults_captured int(11) NOT NULL DEFAULT 0,
  catapults_destroyed int(11) NOT NULL DEFAULT 0,
  attacker_report text,
  defender_report text,
  defender_seen tinyint(1) NOT NULL DEFAULT 0,
  created_at datetime DEFAULT NULL,
  PRIMARY KEY  (id),
  KEY round_created (round_id,created_at),
  KEY attacker_kingdom_id (attacker_kingdom_id),
  KEY defender_kingdom_id (defender_kingdom_id)
) {charset_collate};
CREATE TABLE {prefix}ido_ops (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  round_id bigint(20) unsigned NOT NULL DEFAULT 0,
  actor_kingdom_id bigint(20) unsigned NOT NULL DEFAULT 0,
  target_kingdom_id bigint(20) unsigned NOT NULL DEFAULT 0,
  op_type varchar(32) NOT NULL DEFAULT 'recon',
  outcome varchar(16) NOT NULL DEFAULT 'success',
  agent_lost tinyint(1) NOT NULL DEFAULT 0,
  actor_report text,
  target_report text,
  target_seen tinyint(1) NOT NULL DEFAULT 0,
  created_at datetime DEFAULT NULL,
  PRIMARY KEY  (id),
  KEY round_created (round_id,created_at),
  KEY actor_kingdom_id (actor_kingdom_id),
  KEY target_kingdom_id (target_kingdom_id)
) {charset_collate};
CREATE TABLE {prefix}ido_news (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  round_id bigint(20) unsigned NOT NULL DEFAULT 0,
  event_type varchar(32) NOT NULL DEFAULT '',
  message text,
  created_at datetime DEFAULT NULL,
  PRIMARY KEY  (id),
  KEY round_created (round_id,created_at)
) {charset_collate};
CREATE TABLE {prefix}ido_hall (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  round_id bigint(20) unsigned NOT NULL DEFAULT 0,
  round_name varchar(100) NOT NULL DEFAULT '',
  position int(11) NOT NULL DEFAULT 0,
  kingdom_name varchar(60) NOT NULL DEFAULT '',
  ruler_name varchar(60) NOT NULL DEFAULT '',
  user_id bigint(20) unsigned NOT NULL DEFAULT 0,
  title varchar(40) NOT NULL DEFAULT '',
  networth bigint(20) NOT NULL DEFAULT 0,
  land int(11) NOT NULL DEFAULT 0,
  attacks_won int(11) NOT NULL DEFAULT 0,
  recorded_at datetime DEFAULT NULL,
  PRIMARY KEY  (id),
  KEY round_position (round_id,position)
) {charset_collate};
CREATE TABLE {prefix}ido_admin_log (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  event_type varchar(32) NOT NULL DEFAULT '',
  message text,
  user_id bigint(20) unsigned NOT NULL DEFAULT 0,
  created_at datetime DEFAULT NULL,
  PRIMARY KEY  (id),
  KEY created_at (created_at)
) {charset_collate};
