CREATE TABLE {prefix}ido_leagues (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  league_uuid varchar(36) NOT NULL DEFAULT '',
  league_name varchar(100) NOT NULL DEFAULT '',
  hub_url varchar(255) NOT NULL DEFAULT '',
  site_uuid varchar(36) NOT NULL DEFAULT '',
  site_name varchar(100) NOT NULL DEFAULT '',
  site_url varchar(255) NOT NULL DEFAULT '',
  is_originator tinyint(1) NOT NULL DEFAULT 0,
  ruleset_version int(11) NOT NULL DEFAULT 1,
  ruleset longtext,
  fingerprint varchar(64) NOT NULL DEFAULT '',
  round_starts_at datetime DEFAULT NULL,
  round_days int(11) NOT NULL DEFAULT 90,
  muster_days int(11) NOT NULL DEFAULT 5,
  delay_min_days int(11) NOT NULL DEFAULT 3,
  delay_max_days int(11) NOT NULL DEFAULT 8,
  max_sites int(11) NOT NULL DEFAULT 12,
  status varchar(16) NOT NULL DEFAULT 'active',
  paused tinyint(1) NOT NULL DEFAULT 0,
  created_at datetime DEFAULT NULL,
  PRIMARY KEY  (id),
  UNIQUE KEY league_uuid (league_uuid),
  KEY status (status)
) {charset_collate};
CREATE TABLE {prefix}ido_sites (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  league_id bigint(20) unsigned NOT NULL DEFAULT 0,
  site_uuid varchar(36) NOT NULL DEFAULT '',
  site_name varchar(100) NOT NULL DEFAULT '',
  site_url varchar(255) NOT NULL DEFAULT '',
  secret varchar(128) NOT NULL DEFAULT '',
  is_hub tinyint(1) NOT NULL DEFAULT 0,
  status varchar(16) NOT NULL DEFAULT 'pending',
  seq_out bigint(20) unsigned NOT NULL DEFAULT 0,
  seq_in bigint(20) unsigned NOT NULL DEFAULT 0,
  epoch int(11) NOT NULL DEFAULT 1,
  peer_epoch int(11) NOT NULL DEFAULT 1,
  fingerprint varchar(64) NOT NULL DEFAULT '',
  empire_count int(11) NOT NULL DEFAULT 0,
  networth bigint(20) NOT NULL DEFAULT 0,
  largest_networth bigint(20) NOT NULL DEFAULT 0,
  grace_until datetime DEFAULT NULL,
  claimed_at datetime DEFAULT NULL,
  last_contact_at datetime DEFAULT NULL,
  created_at datetime DEFAULT NULL,
  PRIMARY KEY  (id),
  UNIQUE KEY league_site (league_id,site_uuid),
  KEY status (status)
) {charset_collate};
CREATE TABLE {prefix}ido_invites (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  league_id bigint(20) unsigned NOT NULL DEFAULT 0,
  token_hash varchar(64) NOT NULL DEFAULT '',
  note varchar(100) NOT NULL DEFAULT '',
  expires_at datetime DEFAULT NULL,
  used_at datetime DEFAULT NULL,
  used_by varchar(255) NOT NULL DEFAULT '',
  created_at datetime DEFAULT NULL,
  PRIMARY KEY  (id),
  UNIQUE KEY token_hash (token_hash),
  KEY league_id (league_id)
) {charset_collate};
CREATE TABLE {prefix}ido_packets_in (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  league_id bigint(20) unsigned NOT NULL DEFAULT 0,
  peer_id bigint(20) unsigned NOT NULL DEFAULT 0,
  uuid varchar(36) NOT NULL DEFAULT '',
  packet_type varchar(24) NOT NULL DEFAULT '',
  sequence bigint(20) unsigned NOT NULL DEFAULT 0,
  received_at datetime DEFAULT NULL,
  process_after datetime DEFAULT NULL,
  processed_at datetime DEFAULT NULL,
  status varchar(16) NOT NULL DEFAULT 'staged',
  payload longtext,
  result_note text,
  PRIMARY KEY  (id),
  UNIQUE KEY peer_uuid (peer_id,uuid),
  KEY due (status,process_after)
) {charset_collate};
CREATE TABLE {prefix}ido_packets_out (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  league_id bigint(20) unsigned NOT NULL DEFAULT 0,
  peer_id bigint(20) unsigned NOT NULL DEFAULT 0,
  uuid varchar(36) NOT NULL DEFAULT '',
  packet_type varchar(24) NOT NULL DEFAULT '',
  created_at datetime DEFAULT NULL,
  send_after datetime DEFAULT NULL,
  attempts int(11) NOT NULL DEFAULT 0,
  last_attempt_at datetime DEFAULT NULL,
  status varchar(16) NOT NULL DEFAULT 'queued',
  last_error varchar(190) NOT NULL DEFAULT '',
  payload longtext,
  PRIMARY KEY  (id),
  UNIQUE KEY peer_uuid (peer_id,uuid),
  KEY due (status,send_after)
) {charset_collate};
